### ISSUE TITLE
dsl du derangement

### ISSUE THREAD

**Issue by mimiossart** [papabaldas/cfx-target#2]
slt jai le meme soucis pour mes notif du job norauto annonce ouverture fermeture fonctionne pas tu avait fait comment pour me les reparer?

**Comment by papabaldas** [comment]
Dans le fichier server.lua du job tu doit avoir comme sur la photo 
![Capture d'écran 2023-12-27 193346](https://github.com/papabaldas/cfx-target/assets/65123019/998ad850-ea3a-478e-be35-d77d1c77ac28)


Il suffit de désactivé les notifs de okok et de reactiver les notifs esx:showAdvancedNotification

**Comment by mimiossart** [comment]
AddEventHandler('Ouvre:mechanic', function()
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)
	local xPlayers	= ESX.GetPlayers()
	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		TriggerClientEvent('esx:showAdvancedNotification', xPlayers[i], 'Norauto', '~p~Entreprise', 'Le norauto est désormais ~g~Ouvert~s~ !', 'CHAR_MICHAEL', 8)
		-- TriggerClientEvent('okokNotify:Alert', xPlayers[i], "Entreprise Norauto", "Le norauto est dÃ©sormais Ouvert !", 5000, 'neutral')
	end

**Comment by papabaldas** [comment]
C'est qu'il doit en avoir un autre dans le fichier server.lua .

**Comment by mimiossart** [comment]
![210](https://github.com/papabaldas/cfx-target/assets/103827556/ebeecb55-0f74-4a33-ba2d-fa0f94e557f9)

**Comment by papabaldas** [comment]
regarde plus bas tu as encore une notif okok d'activé.

**Comment by mimiossart** [comment]
ESX = nil
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
ESX = exports["es_extended"]:getSharedObject()
TriggerEvent('esx_phone:registerNumber', 'norauto', 'alerte norauto', true, true)

TriggerEvent('esx_society:registerSociety', 'norauto', 'norauto', 'society_norauto', 'society_norauto', 'society_norauto', {type = 'public'})

RegisterServerEvent('Ouvre:mechanic')
AddEventHandler('Ouvre:mechanic', function()
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)
	local xPlayers	= ESX.GetPlayers()
	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		TriggerClientEvent('esx:showAdvancedNotification', xPlayers[i], 'Norauto', '~p~Entreprise', 'Le norauto est désormais ~g~Ouvert~s~ !', 'CHAR_MICHAEL', 8)
		-- TriggerClientEvent('okokNotify:Alert', xPlayers[i], "Entreprise Norauto", "Le norauto est dÃ©sormais Ouvert !", 5000, 'neutral')
	end
end)

RegisterServerEvent('Ferme:mechanic')
AddEventHandler('Ferme:mechanic', function()
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)
	local xPlayers	= ESX.GetPlayers()
	for i=1, #xPlayers, 1 do
		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])
		-- TriggerClientEvent('esx:showAdvancedNotification', xPlayers[i], 'Norauto', '~p~Entreprise', 'Le norauto est désormais ~r~Fermer~s~ !', 'CHAR_MICHAEL', 8)
		TriggerClientEvent('okokNotify:Alert', xPlayers[i], "Entreprise Norauto", "Le norauto est dÃ©sormais Fermer !", 5000, 'neutral')

	end
end)


RegisterServerEvent('esx_mecanojob:prendreitems')
AddEventHandler('esx_mecanojob:prendreitems', function(itemName, count)
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)
	local sourceItem = xPlayer.getInventoryItem(itemName)

	TriggerEvent('esx_addoninventory:getSharedInventory', 'society_norauto', function(inventory)
		local inventoryItem = inventory.getItem(itemName)

		if count > 0 and inventoryItem.count >= count then

			if sourceItem.limit ~= -1 and (sourceItem.count + count) > sourceItem.limit then
				TriggerClientEvent('esx:showNotification', _source, "quantité invalide")
			else
				inventory.removeItem(itemName, count)
				xPlayer.addInventoryItem(itemName, count)
				TriggerClientEvent('esx:showNotification', _source, 'Objet retiré', count, inventoryItem.label)
			end
		else
			TriggerClientEvent('esx:showNotification', _source, "quantité invalide")
		end
	end)
end)


RegisterNetEvent('esx_mecanojob:stockitem')
AddEventHandler('esx_mecanojob:stockitem', function(itemName, count)
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(source)
	local sourceItem = xPlayer.getInventoryItem(itemName)

	TriggerEvent('esx_addoninventory:getSharedInventory', 'society_norauto', function(inventory)
		local inventoryItem = inventory.getItem(itemName)

		-- does the player have enough of the item?
		if sourceItem.count >= count and count > 0 then
			xPlayer.removeInventoryItem(itemName, count)
			inventory.addItem(itemName, count)
			TriggerClientEvent('esx:showNotification', _source, "Objet déposé "..count..""..inventoryItem.label.."")
		else
			TriggerClientEvent('esx:showNotification', _source, "quantité invalide")
		end
	end)
end)


ESX.RegisterServerCallback('esx_mecanojob:inventairejoueur', function(source, cb)
	local xPlayer = ESX.GetPlayerFromId(source)
	local items   = xPlayer.inventory

	cb({items = items})
end)

ESX.RegisterServerCallback('esx_mecanojob:prendreitem', function(source, cb)
	TriggerEvent('esx_addoninventory:getSharedInventory', 'society_norauto', function(inventory)
		cb(inventory.items)
	end)
end)


-- Mission 

RegisterNetEvent("mecano:EndMission")
AddEventHandler("mecano:EndMission", function(job)
    local xPlayer = ESX.GetPlayerFromId(source)

    if xPlayer.job.name ~= "norauto" then
        TriggerEvent("AC:Violations", 24, "Event: mecano:EndMission job: "..xPlayer.job.name, source)
        return
    end

    local gain = math.random(150,300)
    xPlayer.addMoney(gain)

    TriggerEvent('esx_addonaccount:getSharedAccount', 'society_norauto', function(account)
        if account ~= nil then
            societyAccount = account
            societyAccount.addMoney(gain * 2)
        end
    end)

    TriggerClientEvent("esx:showNotification", source, "Vous avez terminé votre mission.\nGain: ~g~"..gain.."~s~€\nGain entreprise: ~g~".. tostring(gain * 2) .."~s~€", "CHAR_LAZLOW", 5000, "danger")
end)


-- Farm

RegisterNetEvent('recolteboulont')
AddEventHandler('recolteboulont', function()
    local item = "boulont"
    local limiteitem = 50
    local xPlayer = ESX.GetPlayerFromId(source)
    local nbitemdansinventaire = xPlayer.getInventoryItem(item).count
    

    if nbitemdansinventaire >= limiteitem then
        TriggerClientEvent('esx:showNotification', source, "Ta pas assez de place dans ton inventaire!")
        recoltepossible = false
    else
        xPlayer.addInventoryItem(item, 1)
        TriggerClientEvent('esx:showNotification', source, "Récolte en cours...")
		return
    end
end)

RegisterNetEvent('traitementkitrepa')
AddEventHandler('traitementkitrepa', function()
    local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)

    local boulont = xPlayer.getInventoryItem('boulont').count
    local kitrepa = xPlayer.getInventoryItem('kitrepa').count

    if kitrepa > 50 then
        TriggerClientEvent('esx:showNotification', source, '~r~Il semble que tu ne puisses plus porter de boulont...')
    elseif boulont < 3 then
        TriggerClientEvent('esx:showNotification', source, '~r~Pas assez de boulont pour traiter...')
    else
        xPlayer.removeInventoryItem('boulont', 5)
        xPlayer.addInventoryItem('kitrepa', 1)    
    end
end)


RegisterServerEvent('sellkitrepa')
AddEventHandler('sellkitrepa', function()
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)
    local kitrepa = 0

	for i=1, #xPlayer.inventory, 1 do
		local item = xPlayer.inventory[i]

		if item.name == "kitrepa" then
			kitrepa = item.count
		end
	end
    
    TriggerEvent('esx_addonaccount:getSharedAccount', 'society_norauto', function(account)
        societyAccount = account
    end)
    
    if kitrepa > 0 then
        xPlayer.removeInventoryItem('kitrepa', 1)
        xPlayer.addMoney(40)
        societyAccount.addMoney(40)
        TriggerClientEvent('esx:showNotification', xPlayer.source, "~g~Vous avez gagner ~b~40$~g~ pour chaque vente d'un kit de réparation")
        TriggerClientEvent('esx:showNotification', xPlayer.source, "~g~La société gagne ~b~40$~g~ pour chaque vente d'un kit de réparation")
    else 
        TriggerClientEvent('esx:showNotification', xPlayer.source, "Vous n'avez plus rien à vendre")
    end
end)

**Comment by papabaldas** [comment]
J'ai supprimer t'on message , ne met pas t'es code ici. 

Il suffit simplement de chercher toute les notif avec okok et de les désactiver. 

Celui ou la notif d'ouverture et bonne le okok est désactivé, mais regarde a celui de la fermeture 
il n'ai pas désactivé le okok

**Comment by mimiossart** [comment]
merci

**Comment by mimiossart** [comment]
ba pourtant jai exactement le meme truc ecrit je comprend pas

**Comment by papabaldas** [comment]
Envoie moi t'on fichier sur discord je vais te le faire.

**Comment by mimiossart** [comment]
tu acept pas les dm
